use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
use aes_gcm::aead::{Aead, OsRng};
use rand::RngCore;
use sha2::{Sha256, Digest};
use std::fs;
use std::io::{self, Write};
use std::path::Path;
use tracing::{info, warn, error};
use zeroize::Zeroize;

/// Environment types
#[derive(Debug, Clone, PartialEq)]
pub enum Environment {
    Development,
    Staging,
    Production,
}

impl Environment {
    pub fn from_str(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "prod" | "production" => Environment::Production,
            "stage" | "staging" => Environment::Staging,
            _ => Environment::Development,
        }
    }

    pub fn env_file_name(&self) -> &str {
        match self {
            Environment::Development => ".env",
            Environment::Staging => ".env.staging",
            Environment::Production => ".env.production",
        }
    }

    pub fn encrypted_file_name(&self) -> String {
        format!("{}.encrypted", self.env_file_name())
    }
}

/// Secure environment file manager with password protection
pub struct SecureEnvManager {
    env_path: String,
    encrypted_path: String,
    environment: Environment,
}

impl SecureEnvManager {
    pub fn new(env_path: &str) -> Self {
        let environment = Self::detect_environment();
        let encrypted_path = format!("{}.encrypted", env_path);
        
        Self {
            env_path: env_path.to_string(),
            encrypted_path,
            environment,
        }
    }

    /// Create manager for specific environment
    pub fn for_environment(env: Environment) -> Self {
        let env_path = env.env_file_name();
        let encrypted_path = env.encrypted_file_name();
        
        info!("🌍 Managing environment: {:?}", env);
        
        Self {
            env_path: env_path.to_string(),
            encrypted_path,
            environment: env,
        }
    }

    /// Detect environment from APP_ENV or NODE_ENV
    fn detect_environment() -> Environment {
        let env_var = std::env::var("APP_ENV")
            .or_else(|_| std::env::var("NODE_ENV"))
            .unwrap_or_else(|_| "development".to_string());
        
        Environment::from_str(&env_var)
    }

    /// Generate a complete .env file with all required fields
    pub fn generate_env_template(&self) -> Result<(), Box<dyn std::error::Error>> {
        info!("📝 Generating .env template...");

        if Path::new(&self.env_path).exists() {
            warn!("⚠️  .env file already exists at {}", self.env_path);
            print!("Overwrite? (y/N): ");
            io::stdout().flush()?;
            
            let mut input = String::new();
            io::stdin().read_line(&mut input)?;
            
            if !input.trim().to_lowercase().starts_with('y') {
                info!("Cancelled - existing file preserved");
                return Ok(());
            }
        }

        // Generate secure random values
        let jwt_secret = Self::generate_secure_random(64);
        let encryption_key = Self::generate_secure_random_hex(32);
        let api_key = Self::generate_secure_random(32);
        let api_secret = Self::generate_secure_random(48);
        let session_secret = Self::generate_secure_random(64);

        let template = format!(r#"# ===========================================
# Secure Environment Configuration
# Generated by env-manager
# Auto-generated secure secrets included
# ===========================================

# -------------------------
# 🧩 Application Settings
# -------------------------
APP_NAME=SecureConfigApp
APP_ENV={}
APP_PORT=8080
APP_LOG_LEVEL=info

# -------------------------
# 🗄️ Database Configuration
# -------------------------
DATABASE_URL=postgresql://user:password@localhost:5432/mydb
DATABASE_POOL_SIZE=10
DATABASE_TIMEOUT=30

# -------------------------
# 🔐 Auto-Generated Secrets (Development Mode)
# These are auto-generated for local development
# In production, use Vault paths below instead
# -------------------------
JWT_SECRET={}
SESSION_SECRET={}
API_KEY={}
API_SECRET={}
ENCRYPTION_KEY={}
JWT_EXPIRY_HOURS=24

# -------------------------
# ☁️ Vault Configuration (Production Mode)
# Uncomment and configure for production deployment
# When configured, secrets will be fetched from Vault
# instead of using the auto-generated values above
# -------------------------
# SECRETS_PROVIDER=vault
# VAULT_ADDR=http://vault.service:8200
# VAULT_AUTH_METHOD=kubernetes
# VAULT_ROLE=secure-app-role
# VAULT_TOKEN=your_vault_token  # Only for local testing

# -------------------------
# 🔑 Secret Paths (Vault Pointers)
# These point to where secrets are stored in Vault
# The app will fetch actual values from these paths
# -------------------------
# SECRET_JWT_PATH=secret/data/secure-app/jwt
# SECRET_SESSION_PATH=secret/data/secure-app/session
# SECRET_API_PATH=secret/data/secure-app/api
# SECRET_DB_PATH=database/creds/secure-app
# SECRET_ENCRYPTION_PATH=secret/data/secure-app/encryption

# -------------------------
# 🌐 Web3 Configuration (Optional)
# -------------------------
# WEB3_PRIVATE_KEY=__VAULT_ONLY__  # Never store in .env!
# WEB3_RPC_URL=https://mainnet.infura.io/v3/YOUR_PROJECT_ID
# WEB3_SIGNER_SERVICE=http://signer-service:8080

# -------------------------
# 🛡️ Security Controls
# -------------------------
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
CORS_ENABLED=true
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=3600

# -------------------------
# 🚨 Safety Controls & Circuit Breakers
# -------------------------
MAX_WITHDRAWAL_LIMIT=100000
BRIDGE_DAILY_LIMIT=1000000
ENABLE_GLOBAL_PAUSE=false
ANOMALY_THRESHOLD=0.8
POLICY_ENGINE_ENABLED=true
POLICY_MODE=strict

# -------------------------
# 🔄 Secret Rotation Config
# -------------------------
SECRET_REFRESH_INTERVAL=300   # seconds
SECRET_MAX_TTL=900            # seconds
ENABLE_AUTO_ROTATION=true

# -------------------------
# 📊 Observability
# -------------------------
METRICS_ENABLED=true
METRICS_PORT=9090
TRACING_ENABLED=true

# -------------------------
# 🧠 Feature Flags
# -------------------------
ENABLE_BRIDGE=true
ENABLE_AIRDROP=false
ENABLE_SIMULATION_ENGINE=true
ENABLE_DEBUG_MODE=false

# -------------------------
# 📧 Email/Notifications (Optional)
# -------------------------
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your_email@gmail.com
# SMTP_PASS=__VAULT__

# -------------------------
# 📱 Telegram Notifications
# -------------------------
# TELEGRAM_BOT_TOKEN=your_bot_token_here
# TELEGRAM_CHAT_ID=your_chat_id_here
"#, 
            match self.environment {
                Environment::Development => "development",
                Environment::Staging => "staging",
                Environment::Production => "production",
            },
            jwt_secret,
            session_secret,
            api_key,
            api_secret,
            encryption_key
        );

        fs::write(&self.env_path, template)?;
        info!("✅ .env template created at: {}", self.env_path);
        info!("🔐 Auto-generated secure secrets (for development):");
        info!("   - JWT_SECRET (64 chars)");
        info!("   - SESSION_SECRET (64 chars)");
        info!("   - API_KEY (32 chars)");
        info!("   - API_SECRET (48 chars)");
        info!("   - ENCRYPTION_KEY (32-byte hex)");
        info!("☁️  Vault configuration section added (for production):");
        info!("   - VAULT_ADDR, VAULT_AUTH_METHOD, VAULT_ROLE");
        info!("   - Secret path pointers (SECRET_*_PATH)");
        info!("🛡️  Safety controls & circuit breakers included:");
        info!("   - MAX_WITHDRAWAL_LIMIT, BRIDGE_DAILY_LIMIT");
        info!("   - ENABLE_GLOBAL_PAUSE, POLICY_ENGINE_ENABLED");
        info!("💡 Tip: Run 'cargo run -- lock' to encrypt and protect this file");
        info!("💡 For production: Uncomment Vault section and comment auto-generated secrets");

        Ok(())
    }

    /// Lock (encrypt) the .env file with password protection
    pub fn lock_env(&self) -> Result<(), Box<dyn std::error::Error>> {
        info!("🔒 Locking .env file with password protection...");

        if !Path::new(&self.env_path).exists() {
            error!("❌ .env file not found at {}", self.env_path);
            return Err(format!(".env file not found at {}", self.env_path).into());
        }

        // Read the .env file
        let env_content = fs::read_to_string(&self.env_path)?;
        
        // Get password from user
        let password = self.prompt_password("Enter encryption password: ")?;
        
        if password.len() < 8 {
            return Err("Password must be at least 8 characters".into());
        }

        // Encrypt the content
        let encrypted_data = self.encrypt_content(&env_content, &password)?;
        
        // Write encrypted file
        fs::write(&self.encrypted_path, &encrypted_data)?;
        
        // Securely delete the plaintext .env file
        self.secure_delete(&self.env_path)?;
        
        info!("✅ .env file locked and encrypted");
        info!("   Encrypted file: {}", self.encrypted_path);
        info!("   Original file: {} (securely deleted)", self.env_path);
        info!("💡 To unlock: cargo run -- unlock");

        Ok(())
    }

    /// Unlock (decrypt) the .env file with password
    pub fn unlock_env(&self) -> Result<(), Box<dyn std::error::Error>> {
        info!("🔓 Unlocking .env file...");

        if !Path::new(&self.encrypted_path).exists() {
            error!("❌ Encrypted file not found at {}", self.encrypted_path);
            return Err(format!("Encrypted file not found at {}", self.encrypted_path).into());
        }

        // Get password from user
        let password = self.prompt_password("Enter decryption password: ")?;

        // Read encrypted file
        let encrypted_data = fs::read(&self.encrypted_path)?;
        
        // Decrypt
        let decrypted_content = self.decrypt_content(&encrypted_data, &password)?;
        
        // Write decrypted .env file
        fs::write(&self.env_path, &decrypted_content)?;
        
        info!("✅ .env file unlocked and decrypted");
        info!("   Decrypted file: {}", self.env_path);
        info!("⚠️  Remember to lock it again after editing: cargo run -- lock");

        Ok(())
    }

    /// Check if .env is currently locked
    pub fn is_locked(&self) -> bool {
        Path::new(&self.encrypted_path).exists() && !Path::new(&self.env_path).exists()
    }

    /// Check if .env is currently unlocked
    pub fn is_unlocked(&self) -> bool {
        Path::new(&self.env_path).exists()
    }

    /// Change password for encrypted .env
    pub fn change_password(&self) -> Result<(), Box<dyn std::error::Error>> {
        info!("🔑 Changing encryption password...");

        if !Path::new(&self.encrypted_path).exists() {
            return Err("No encrypted .env file found. Lock it first.".into());
        }

        // Get old password
        let old_password = self.prompt_password("Enter current password: ")?;
        
        // Decrypt with old password
        let encrypted_data = fs::read(&self.encrypted_path)?;
        let decrypted_content = self.decrypt_content(&encrypted_data, &old_password)?;
        
        // Get new password
        let new_password = self.prompt_password("Enter new password: ")?;
        
        if new_password.len() < 8 {
            return Err("New password must be at least 8 characters".into());
        }

        let confirm_password = self.prompt_password("Confirm new password: ")?;
        
        if new_password != confirm_password {
            return Err("Passwords do not match".into());
        }

        // Re-encrypt with new password
        let new_encrypted = self.encrypt_content(&decrypted_content, &new_password)?;
        fs::write(&self.encrypted_path, &new_encrypted)?;
        
        info!("✅ Password changed successfully");

        Ok(())
    }

    // Private helper methods

    /// Prompt for password (hidden input)
    fn prompt_password(&self, prompt: &str) -> Result<String, Box<dyn std::error::Error>> {
        print!("{}", prompt);
        io::stdout().flush()?;
        
        // Read password (in production, use rpassword crate for hidden input)
        let mut password = String::new();
        io::stdin().read_line(&mut password)?;
        
        Ok(password.trim().to_string())
    }

    /// Encrypt content with password-derived key
    fn encrypt_content(&self, content: &str, password: &str) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        // Derive key from password using SHA-256
        let mut hasher = Sha256::new();
        hasher.update(password.as_bytes());
        let key_bytes = hasher.finalize();
        
        let key = aes_gcm::Key::<Aes256Gcm>::from_slice(&key_bytes);
        let cipher = Aes256Gcm::new(key);
        
        // Generate random nonce
        let mut nonce_bytes = [0u8; 12];
        OsRng.fill_bytes(&mut nonce_bytes);
        let nonce = Nonce::from_slice(&nonce_bytes);
        
        // Encrypt
        let ciphertext = cipher.encrypt(nonce, content.as_bytes())
            .map_err(|e| format!("Encryption failed: {}", e))?;
        
        // Combine nonce + ciphertext
        let mut result = Vec::new();
        result.extend_from_slice(&nonce_bytes);
        result.extend_from_slice(&ciphertext);
        
        Ok(result)
    }

    /// Decrypt content with password-derived key
    fn decrypt_content(&self, encrypted_data: &[u8], password: &str) -> Result<String, Box<dyn std::error::Error>> {
        if encrypted_data.len() < 13 {
            return Err("Invalid encrypted data".into());
        }

        // Derive key from password
        let mut hasher = Sha256::new();
        hasher.update(password.as_bytes());
        let key_bytes = hasher.finalize();
        
        let key = aes_gcm::Key::<Aes256Gcm>::from_slice(&key_bytes);
        let cipher = Aes256Gcm::new(key);
        
        // Extract nonce and ciphertext
        let (nonce_bytes, ciphertext) = encrypted_data.split_at(12);
        let nonce = Nonce::from_slice(nonce_bytes);
        
        // Decrypt
        let plaintext = cipher.decrypt(nonce, ciphertext)
            .map_err(|_| "Decryption failed - wrong password or corrupted data")?;
        
        let content = String::from_utf8(plaintext)
            .map_err(|_| "Decrypted data is not valid UTF-8")?;
        
        Ok(content)
    }

    /// Securely delete a file (overwrite before deletion)
    fn secure_delete(&self, path: &str) -> Result<(), Box<dyn std::error::Error>> {
        if !Path::new(path).exists() {
            return Ok(());
        }

        // Overwrite file with random data multiple times
        let file_size = fs::metadata(path)?.len();
        
        for _ in 0..3 {
            let random_data: Vec<u8> = (0..file_size)
                .map(|_| rand::random::<u8>())
                .collect();
            fs::write(path, &random_data)?;
        }
        
        // Delete the file
        fs::remove_file(path)?;
        
        info!("🗑️  Securely deleted: {}", path);
        Ok(())
    }

    /// Generate cryptographically secure random string
    fn generate_secure_random(length: usize) -> String {
        use rand::Rng;
        let mut rng = rand::thread_rng();
        
        const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";
        let result: String = (0..length)
            .map(|_| {
                let idx = rng.gen_range(0..CHARSET.len());
                CHARSET[idx] as char
            })
            .collect();
        
        result
    }

    /// Generate cryptographically secure random hex string
    fn generate_secure_random_hex(length: usize) -> String {
        use rand::Rng;
        let mut rng = rand::thread_rng();
        
        let bytes: Vec<u8> = (0..length).map(|_| rng.gen()).collect();
        hex::encode(bytes)
    }
}

impl Drop for SecureEnvManager {
    fn drop(&mut self) {
        // Ensure sensitive data is zeroized
        self.env_path.zeroize();
        self.encrypted_path.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_encrypt_decrypt_cycle() {
        let manager = SecureEnvManager::new("/tmp/test.env");
        let original = "SECRET_KEY=test_value\nDB_PASSWORD=secret123";
        let password = "test_password_123";

        let encrypted = manager.encrypt_content(original, password).unwrap();
        let decrypted = manager.decrypt_content(&encrypted, password).unwrap();

        assert_eq!(original, decrypted);
    }

    #[test]
    fn test_wrong_password_fails() {
        let manager = SecureEnvManager::new("/tmp/test.env");
        let original = "SECRET=test";
        let password = "correct_password";
        let wrong_password = "wrong_password";

        let encrypted = manager.encrypt_content(original, password).unwrap();
        let result = manager.decrypt_content(&encrypted, wrong_password);

        assert!(result.is_err());
    }

    #[test]
    fn test_generate_template() {
        let manager = SecureEnvManager::new("/tmp/test_template.env");
        let result = manager.generate_env_template();
        
        assert!(result.is_ok());
        assert!(Path::new("/tmp/test_template.env").exists());
        
        // Cleanup
        fs::remove_file("/tmp/test_template.env").ok();
    }
}
